spring.application.name=jokes-mvc

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

jokes-mvc.openai.url=https://api.openai.com/v1
jokes-mvc.openai.api-key=set-through-env-var-for-each-environment
jokes-mvc.openai.model=gpt-3.5-turbo

jokes-mvc.icanhazdadjoke.url=https://icanhazdadjoke.com

# No migrations yet. Re-enable when db/migration is added.
spring.flyway.enabled=false
